jQuery(document).ready(function($){var bootstrapButton=$.fn.button.noConflict()
$.fn.bootstrapBtn=bootstrapButton
if($('.bxslider').length){$('.bxslider').bxSlider({pagerCustom:'#bx-pager'});}
if($('.progressbars').length){$(".progressbars").jprogress();$(".progressbarsone").jprogress({});}
if($('.product-detail-slider').length){$(".product-detail-slider").owlCarousel({navigation:true,items:3,loop:true,margin:30,itemsCustom:false,itemsDesktop:[1199,2],itemsDesktopSmall:[979,2],itemsTablet:[768,2],itemsTabletSmall:false,itemsMobile:[479,1],singleItem:false,itemsScaleUp:false,});}
if($('.product-detail-slider-2').length){$(".product-detail-slider-2").owlCarousel({navigation:true,items:4,loop:true,margin:30,itemsCustom:false,itemsDesktop:[1199,2],itemsDesktopSmall:[979,2],itemsTablet:[768,2],itemsTabletSmall:false,itemsMobile:[479,1],singleItem:false,itemsScaleUp:false,});}
if($('.charity-slider').length){$(".charity-slider").owlCarousel({navigation:true,items:3,loop:true,margin:30,itemsCustom:false,itemsDesktop:[1199,2],itemsDesktopSmall:[979,2],itemsTablet:[768,2],itemsTabletSmall:false,itemsMobile:[479,1],singleItem:false,itemsScaleUp:false,});}
if($('#defaultCountdown').length){var austDay=new Date();austDay=new Date(austDay.getFullYear()+ 1,1- 1,26);$('#defaultCountdown').countdown({until:austDay});$('#year').text(austDay.getFullYear());}
if($('#cp_side-menu-btn, #cp-close-btn').length){$('#cp_side-menu-btn, #cp-close-btn').on('click',function(e){var $navigacia=$('body, #cp_side-menu'),val=$navigacia.css('right')==='410px'?'0px':'410px';$navigacia.animate({right:val},410)});}
$('#lyrics').on('click',function(){$("#dialog").dialog();});if($('#search-push').length){$('#search-push').on('click',function(){var $navigacia=$('#cp-slide-search');var $val=($navigacia.width());if($val=='0'){$val='100%';$('#cp-slide-search form input[type="text"]').css({padding:'0 30px',});}else{$val='0';$('#cp-slide-search form input[type="text"]').css({padding:'0',transition:'all ease-in-out 0.8s',});}
$navigacia.animate({width:$val},600)});}
if($('audio').length){$('audio').audioPlayer();}
if($('#content-1').length){$("#content-1").mCustomScrollbar({horizontalScroll:false});$(".content.inner").mCustomScrollbar({scrollButtons:{enable:true}});}
if($('#home-banner').length){$("#home-banner").owlCarousel({navigation:true,slideSpeed:300,paginationSpeed:400,autoPlay:true,autoplayTimeout:1000,singleItem:true});}
if($('#client-banner').length){$("#client-banner").owlCarousel({navigation:true,slideSpeed:300,paginationSpeed:400,autoPlay:true,autoplayTimeout:1000,singleItem:true});}
if($('.defaultCountdown').length){var austDay=new Date();austDay=new Date(austDay.getFullYear()+ 1,1- 1,26);$('.defaultCountdown').countdown({until:austDay});$('#year').text(austDay.getFullYear());}
if($('.store-banner').length){$(".store-banner").owlCarousel({navigation:true,slideSpeed:300,paginationSpeed:400,autoPlay:true,autoplayTimeout:1000,singleItem:true});}
if($('#product-banner').length){$("#product-banner").owlCarousel({navigation:true,slideSpeed:300,paginationSpeed:400,autoPlay:true,autoplayTimeout:1000,singleItem:true});}
if($('.store-banner').length){$(".store-banner").owlCarousel({navigation:true,slideSpeed:300,paginationSpeed:400,autoPlay:true,autoplayTimeout:1000,singleItem:true});}
if($('.countdown').length){$('.countdown').final_countdown({'start':1362139200,'end':1388461320,'now':1387461319});}
$('#blog-masonrywrap li div div a img').load(function(){attWorkGrid_1();});if($('.accordion_cp').length){$.fn.slideFadeToggle=function(speed,easing,callback){return this.animate({opacity:'toggle',height:'toggle'},speed,easing,callback);};$('.accordion_cp').accordion({defaultOpen:'section1',cookieName:'nav',speed:'slow',animateOpen:function(elem,opts){elem.next().stop(true,true).slideFadeToggle(opts.speed);},animateClose:function(elem,opts){elem.next().stop(true,true).slideFadeToggle(opts.speed);}});}
if($('#calendar-2').length){$('#calendar-2').fullCalendar({defaultDate:'2016-06-12',editable:true,eventLimit:true,events:[{title:'School of the Prophets and learn',start:'2016-08-01'},{title:'Long Event',start:'2016-08-07',end:'2016-06-10'},{id:999,title:'Single Life Workshop 3.5-Day Intensive',start:'2016-08-09T16:00:00'},{title:'Open Heavens Leaders School',start:'2016-09-12T10:30:00',end:'2016-06-12T12:30:00'},{title:'Love After Marriage',start:'2016-08-12T14:30:00'},]});}
if($('#calendar').length){var date=new Date();var d=date.getDate();var m=date.getMonth();var y=date.getFullYear();$('#calendar').fullCalendar({editable:true,});}
if($('#popup-overlay').length){$('#popup-overlay').fadeIn(500,function(){$('#popup').show();$('#popup').css({"top":"200px","opacity":"1","visibility":"visible"});});$("#popup-close").on('click',function(){$('#popup-overlay').css({"display":"none","visibility":"hidden"});});}});